INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Leticia');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Medellin');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Arauca');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Barranquilla');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Santa Marta');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Bogotá');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Cartagena');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Tunja');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Valledupar');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Neiva');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Armenia');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Ibague');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Cúcuta');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Bucaramanga');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Riohacha');
INSERT INTO `city` (`id`, `name`) VALUES (NULL, 'Monteria');